name: openfoam

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: setup  openfoam
      run: |
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install openfoam2012-dev
    - name: compile library
      run: |
        openfoam2012 -c ./Allwmake
    - name: test
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        openfoam2012 -c py.test
